
const reponeSucessCode = 200; //服务器返回的成功Code

const localImg = "../../static/images/";


//扫码成功  相关Code
const    EXISTS_UNPAID_BILL = 510;
const    USE_DEVICE_NOT_CLOSED = 511;
const    DEVICE_BASE_STATUS_EXCEPTION = 512;
const    DEVICE_STATUS_BEING_USE = 513;
const    DEVICE_STATUS_USE_EXCEPTION = 514;
const    DEVICE_USE_UNLOCK_FAILD = 515;
const    DEVICE_USE_RUNNING = 516;
const    NOT_NEED_DEVICE = 517;
const    NOT_NETWORK_DEVICE = 518;
const    BUSINESS_TIME = 499;
const    QCODE_ERROR = 498;
const    FORCE_NEED_ADVANCE_MONEY = 552;
const    NEED_ADVANCE_MONEY = 551;
const    FORCE_NEED_CONFIRM = 553;
const    NEED_ADVANCE_MONEY_DEVICE = 554;
const    BUY_MEMBER_CARD = 555;
const    AUTO_BUY_DOOR_SUCCESS = 557;
const    AUTO_PAY_AMOUNT_NOT_ENOUGH = 1400;



export default {
    reponeSucessCode,
    EXISTS_UNPAID_BILL,
    USE_DEVICE_NOT_CLOSED,
    DEVICE_BASE_STATUS_EXCEPTION,
    DEVICE_STATUS_BEING_USE,
    DEVICE_STATUS_USE_EXCEPTION,
    DEVICE_USE_UNLOCK_FAILD,
    DEVICE_USE_RUNNING,
    NOT_NEED_DEVICE,
    NOT_NETWORK_DEVICE,
    BUSINESS_TIME,
    QCODE_ERROR,
    FORCE_NEED_ADVANCE_MONEY,
    NEED_ADVANCE_MONEY,
    FORCE_NEED_CONFIRM,
    NEED_ADVANCE_MONEY_DEVICE,
    BUY_MEMBER_CARD,
    AUTO_BUY_DOOR_SUCCESS,
    AUTO_PAY_AMOUNT_NOT_ENOUGH,
};
